services:
  # Twój obecny kontener z FastAPI
  fastapi:
    build:
      context: ../..
      dockerfile: deploy/bit/Dockerfile
    command: python -m bit.main
    environment:
      API_KEY: ${API_KEY}
      API_KEY_DEBUG: ${API_KEY_DEBUG}
      DATABASE: ${DATABASE}
      CV_DIRECTORY: ${CV_DIRECTORY}
      EC2_URL: ${EC2_URL}
      NGROK_BASIC_AUTH: ${NGROK_BASIC_AUTH}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ../../cv_files/bit:/app/cv_files
      - ../../data/bit:/app/data
    restart: unless-stopped